spring:
  application:
    name: catalog-service

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 300
        readTimeout: 300
        loggerLevel: full
